hmc_host: "YOUR_HMC_HOSTNAME"  # <-- Supply your HMC host here
hmc_auth:
  userid: "YOUR_HMC_USER"        # <-- Supply your HMC user here
  password: "YOUR_HMC_PASSWORD"    # <-- Supply your HMC password here
  verify: false